### PR TITLE
Allow plugin to run under Netbox 4.X

### PR DESCRIPTION
**Pull request by slyngshede**
There are only a few minor differences between the plugin API in Netbox 3.X and 4.X. This patch should allow the plugin to run under both Netbox 3 and 4.

### CODE REVIEW

**Comment by Pixelshifter** [comment]
Do you have the possibility to test your changes and then call the /api/schema endpoint of Netbox? I get an err with the latest version of this plugin, which hinders my Ansible dynamic inventory integration. I get this error:

```
<class 'AttributeError'>

'MetricValueTypeOptionsViewSet' object has no attribute 'queryset'
```

**Comment by slyngshede** [comment]
@Pixelshifter We do not currently use the /api/schema endpoint for anything, so other than that I now get a YAML file that looks somewhat sane, I can't really validate.

Feel free to reach out if my patch doesn't work for you.

**Comment by TheDJVG** [comment]
Hi everyone,

Thanks a lot for your effort and sorry for the slow replies on my side. Let me take in all the changes, test them with the latest version and do a new release!

Thanks,
Daan

**Comment by TheDJVG** [comment]
Netbox 4 compatibility will be tracked in daan/netbox4. Initial changes and Netbox 4 migrations can be found here: https://github.com/TheDJVG/netbox-more-metrics/commit/3da31f30ec86a074d439db6a21f1c288b28db26a

**Comment by TheDJVG** [comment]
Version 0.3.0 is now released with NetBox 4.0 support!

**Pull request closed without merging**
